### ISSUE TITLE
Fails on spec retry on parallel machines 

### ISSUE THREAD

**Issue by steven-airwallex** [NicholasBoll/cypress-run#2]
Heya,

Thanks for making this. Just wanted to see if you were getting a similar issue to the image attached. 
Seems to not like not having the same list of specs passed to cypress dashboard?

![51094895-cd036b80-1804-11e9-82af-8e4fb8a6997b](https://user-images.githubusercontent.com/35050649/51095174-dbeb1d80-1806-11e9-942e-4919628cce8a.png)

Thanks for making the module by the way!

**Comment by NicholasBoll** [comment]
Sorry. Somehow I missed the notification of this issue. I've been running this script for a while. Do you mind pasting in the line that's run (minus the sensitive info like you're key)

Here's what mine looks like:
```
yarn cypress-run --key ${env.CYPRESS_KEY} --spec cypress/integration/regression/**/* --config baseUrl=https://$xmHostName:8443 --parallel --group regression --ci-build-id=${env.BRANCH_NAME}-${env.BUILD_ID}
```

We're using Jenkins. `env.CYPRESS_KEY`, `env.BRANCH_NAME` and `env.BUILD_ID` comes from the Jenkins environment. `xmHostName` refers to the resolvable address of the VM the application is deployed to.

Note that we did branch name AND build ID for the `--ci-build-id`. If the build id is not unique, Cypress parallel can error. Parallel works by multiple connections are made to the dashboard service within a reasonable amount of time. Some metadata is used to treat those connections as parallel runs of the same test run. `--ci-build-id` is one of those. If that value is not unique between runs, you will run into errors like the one you described. In our case we are using the Jenkins Multibranch plugin which makes a job for each branch and/or PR and they all start with a `BUILD_ID` of 1. For us, the branch name + build number is enough to ensure the value is unique.
